# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GraduatedRenderer
                                 A QGIS plugin
 This plugin renders selected layer to specified number of classes.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-03-29
        copyright            : (C) 2018 by Asad
        email                : asad.abbas@tplmaps.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GraduatedRenderer class from file GraduatedRenderer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .graduated_renderer import GraduatedRenderer
    return GraduatedRenderer(iface)
